on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

permissions:
  contents: write

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build project
        run: |
          make
      - name: Create Release and Upload Asset
        run: |
          gh release create "${GITHUB_REF_NAME}" ./wscat \
            --title "${GITHUB_REF_NAME}" \
            --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
